<?php

$config_mysqli_host = "quentinipbbd.mysql.db";
$config_mysqli_user = "quentinipbbd";
$config_mysqli_mdp = "5fbcMRR6HU5";
$config_mysqli_db = "quentinipbbd";

$config_mysqli_table_session = "MB_base_session";
$config_mysqli_table_user = "MB_base_user";
$config_mysqli_table_module = "MB_module";

$config_account_expire = 1296000; //15 jours
$config_account_recupexpire = 600; //10 minutes

$config_hash_seed = "71150-48206-46298-40348-60741-96450";

$config_safety_domainename = array (
		1 => "127.0.0.1",
		2 => "localhost",
		3 => "quentinix.fr"
	);

?>